### ISSUE TITLE
Initial extension for ckan about page

### ISSUE THREAD

**Issue by sneha-sharma12** [sneha-sharma12/ckanext-learning#1]
When I am extended the ckan application, I want to change the about page user interface, so I can view new look and feel.

## Acceptance

* [x] New extension is created
* [x] New about page is accessible at route `/about`

## Tasks

* [x] Create new extension
* [x] Add new page in template section

## Analysis

Followed the [documentation](https://docs.ckan.org/en/2.9/theming/templates.html#replacing-a-default-template-file) from ckan
